# Test Environment Configuration
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/payflowxdb_test
spring.datasource.username=root
spring.datasource.password=Empire@7062

jwt.secret=asdhahdihdhdksjdkasjdasjdajdjdiadiadiadjaidiasdusdfr

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


logging.level.com.payflowx=DEBUG    
